name: Publish to NuGet

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/Concur.sln

    - name: Build
      run: dotnet build src/Concur.sln --no-restore -c Release

    - name: Pack
      run: dotnet pack src/Concur/Concur.csproj --no-build -c Release -o ./nupkgs

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
